# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'personal-scoreboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for personal-scoreboard

  target 'personal-scoreboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'personal-scoreboardUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'

end
